version: "3"
services:
  clickhouse-server:
    image: yandex/clickhouse-server:19.13.3.26
    container_name: clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

    volumes:
      - ./data/:/var/lib/clickhouse
      - ./conf/config.xml:/etc/clickhouse-server/config.xml

  client:
    image: yandex/clickhouse-client
    command: ['--host', 'clickhouse-server', '--query', 'show databases']
    links:
      - clickhouse-server
