server:
  port: ${APP_PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        - id: crp-main
          uri: ${FIP_MAIN_SERVICE:http://crp-main:8080}
          predicates:
            - Path=/crp/v1/**
          filters:
            - RewritePath= /crp/v1/(?<segment>.*),/$\{segment}

        - id: wa-website
          uri: http://wa-website:80
          predicates:
            - Path=/web/**
          filters:
            - RewritePath= /web/(?<segment>.*),/$\{segment}


logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL:info}
    root: ${LOGGING_LEVEL:info}
