server:
  port: 8090

management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  metrics.export.prometheus.enabled: true
  endpoints.web.exposure.include: '*'

asyn-pool:
  maxRequestQueueLength: ${MAX_REQUEST_QUEUE:10000}
  maxConcurrentRequestNum: ${MAX_REQUEST_NUM:1200}
  coreThreadNum: ${CORE_THREAD_NUM:500}

http-config:
  connectTimeout: ${HTTP_CONN_TIMEOUT:60000}
  readTimeout: ${HTTP_READ_TIMEOUT:60000}
  maxConnectionNum: ${MAX_CONN_NUM:2000}
  maxPerRoute: ${MAX_PER_ROUTE:1200}
  socketTimeout: ${SOCKET_TIMEOUT:60000}

vpp:
  host: ${VPP_HOST:vpp}
  port: ${VPP_PORT:8082}
  debug_external_ip: ${DEBUG_EXTERNAL_IP}

repo:
  url: http://${CVPF_REPO_HOST:repo-manager}:${CVPF_REPO_PORT:8585}
  default_model: ${CVPF_REPO_DEFAULT_MODEL:3060}

p2p-config:
  proxyUrl: ${P2P_PROXY_URL:p2p-component}
  proxyPort: ${P2P_PROXY_PORT:7093}
  p2pInfoPort: ${P2P_SERVICE_PORT:7600}

task-config:
  taskAliveDuration: ${TASK_ALIVE_DURATION:1800000}
  taskTimeOut: ${TASK_TIME_OUT:100000}
  synQueryTimeOut: ${SYN_QUERY_TIME_OUT:60000}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

pilot:
  url: ${PILOT_URL:http://pilot:8080}
  superAdminName: super_admin
  rootPath: /account

mongodb:
  host: ${MONGODB_HOST:fip-mongo}
  port: ${MONGODB_PORT:27017}
  database: fip

cvpf-repository-manager:
  host: ${CVPF_REPO_HOST:repo-manager}
  port: ${CVPF_REPO_PORT:8585}
  model: ${CVPF_REPO_DEFAULT_MODEL:3060}
  part: FACE

license:
  host: ${LICENSE_HOST:127.0.0.1}
  port: ${LICENSE_PORT:7411}
  conn_timeout: 2000
  send_timeout: 2000
  recv_timeout: 6000
  retry_interval: 1000
  retry_times: 0
  license_key: face_identification_platform
  quota_key:
  check_period: 10000
  enabled: ${LICENSE_ENABLED:true}

ragnaros:
  lucifron_host:  ${LUCIFRON_HOST:10.40.80.18}
  lucifron_port:  ${LUCIFRON_PORT:9990}
  local_host:  ${LOCAL_HOST:127.0.0.1}
  video_callback_port: ${VIDEO_CALLBACK_PORT:3456}
  face_image_feature_extract_group:  ${FACE_IMAGE_FEATURE_EXTRACT_GROUP:sample-feature-extract}
  face_anno_image_feature_extract_group:  ${FACE_ANNO_IMAGE_FEATURE_EXTRACT_GROUP:sample-anno-feature-extract}
  verify_group:  ${VERIFY_GROUP:sample-verify}
  face_video_recognition_group:  ${FACE_VIDEO_RECOGNITION_GROUP:sample-face-video}
  face_normalize_group: ${FACE_NORMALIZE_GROUP:sample-face-normalize}
  runtime_config_path:  config/runtime_config.json
  default_face_image_feature_extract_request_path:  config/face_image_feature_extract_request.json
  default_verify_request_path:  config/verify_request.json
  default_face_normalize_request_path: config/face_normalize_request.json
  debug_outside_ragnaros: ${DEBUG_OUTSIDE_RAGNAROS:false}

cluster-info:
  gatewayPort: ${GATEWAY_PORT:9080}
  productName: ${CLUSTER_PRODUCT_NAME:fip}
  productVersion: ${CLUSTER_PRODUCT_VERSION:2.2.a}
  clusterId: ${CLUSTER_ID:}
  clusterName: ${CLUSTER_NAME:}
  province: ${CLUSTER_PROVINCE:}
  city: ${CLUSTER_CITY:}
  county: ${CLUSTER_COUNTY:}
  excludeReportClusters: ${EXCLUDE_REPORT_CLUSTERS:}
  includeReportClusters: ${INCLUDE_REPORT_CLUSTERS:}

job:
  cluster-info-update: ${JOB_CLUSTER_INFO_UPDATE:0 0/1 * * * ?}
  task-maintance:  ${TASK_MAINTANCE:0 0/20 0 * * ?}
  cluster-monitor-collect: ${JOB_CLUSTER_MONITOR_COLLECT:0/30 * * * * ?}
  cluster-monitor-fetch: ${JOB_CLUSTER_MONITOR_FETCH:10/30 * * * * ?}
  cluster-monitor-report: ${JOB_CLUSTER_MONITOR_REPORT:20/30 * * * * ?}
