version: '2'
services:
  zookeeper:
    image: 'it-artifactory.yitu-inc.com/docker-local/big-data/zookeeper:3.4.14'
    ports:
      - '2181:2181'
    volumes:
      - ./config/zoo.cfg:/opt/zookeeper-3.4.14/conf/zoo.cfg
      - ./data/zookeeper:/data/zookeeper
