version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './data/postgresql:/bitnami/postgresql'
  sonarqube:
    image: bitnami/sonarqube:7
    ports:
      - '9002:9000'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1234
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bitnami1234
    volumes:
      - ./data/sonarqube:/bitnami
