version: '2'
networks:
    monitor:
        driver: bridge

services:
    prometheus:
      image: prom/prometheus
      hostname: prometheus
      restart: always
      volumes:
        - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./config/node_down.yml:/etc/prometheus/node_down.yml
        - ./bin/timezone:/etc/timezone
        - ./bin/localtime:/etc/localtime
        - ./data/prometheus:/prometheus
      ports:
        - "19090:9090"
      networks:
        - monitor

    pushgateway:
      image: prom/pushgateway
      ports:
        - "19091:9091"

    alertmanager:
      image: prom/alertmanager
      hostname: alertmanager
      restart: always
#      volumes:
#          - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      ports:
        - "19093:9093"
      networks:
        - monitor

    grafana:
      image: grafana/grafana
      hostname: grafana
      restart: always
      ports:
        - "13000:3000"
      networks:
        - monitor

    node-exporter:
      image: quay.io/prometheus/node-exporter
      hostname: node-exporter
      restart: always
      ports:
        - "19100:9100"
      networks:
        - monitor

    cadvisor:
      image: google/cadvisor:latest
      hostname: cadvisor
      restart: always
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      ports:
        - "18080:8080"
      networks:
        - monitor

