version: "3"
services:
  p2p-api-gateway:
    image: it-artifactory.yitu-inc.com/docker-local/p2p:release_2-0-1-50f90995
    ports:
      - 9080:9080
    volumes:
      - ./config/application.yml:/app/config/application.yml

  p2p-component:
    image: it-artifactory.yitu-inc.com/cvpf-docker/cvpf-p2p:latest
    ports:
      - 7093:7093
      - 8443:8443
      - 7600:7600
    environment:
      SPRING_APPLICATION_JSON: '
                               {
                                 "PROXY_PORT": 7093,
                                 "HTTPS_PORT": 8443,
                                 "HTTP_PORT": 7600,
                                 "current_cluster_id": "SH_SH_001",
                                 "GATEWAY_HOST": "p2p-api-gateway",
                                 "GATEWAY_PORT": 9080,
                                 "p2p": {
                                   "routes": {
                                     "static": {
                                       "directRoute": {
                                         "SH_SH_002": "10.40.57.75:8443:7600"
                                       },
                                       "indirectRoute": {}
                                     }
                                   }
                                 }
                               }
                               '

