PILOT_SERVICE: http://pilot:8080
OAUTH_CLIENT_ID: fipClient
OAUTH_CLIENT_SECRET: 1Tu_Fip_User
FIP_MAIN_SERVICE: http://fip-main:8090
VPP_DATA_SERVICE: http://vpp:8082

server:
  port: ${APP_PORT:8080}
  ssl:
    enabled: true
    key-alias: rsaserver
    key-store-password: rsa123
    key-store: /app/config/rsaserver.keystore

spring:
  cloud:
    gateway:
      routes:
        - id: login
          uri: ${PILOT_SERVICE:http://pilot:8080}
          predicates:
            - Path=/fip/v1/auth/login
          filters:
            - MutateContentType=JSON_TO_FORM_URLENCODED
            - AddOAuthClient=fipClient, 1Tu_Fip_User
            - SetPath=/oauth/token

        - id: vpp_get_video_cover_image
          uri: ${VPP_DATA_SERVICE:http://vpp:8082}
          predicates:
            - Path=/fip/v1/videos/{videoid}/image
            - Method=GET
          filters:
            # 视频元信息
            - SetPath=/api/v1/image/{videoid}

        - id: vpp_get_video_meta
          uri: ${VPP_DATA_SERVICE:http://vpp:8082}
          predicates:
            - Path=/fip/v1/videos/{videoid}/data
            - Method=GET
          filters:
            # 视频元信息
            - SetPath=/api/v1/video/{videoid}/

        - id: vpp_get_video_ts
          uri: ${VPP_DATA_SERVICE:http://vpp:8082}
          predicates:
            - Path=/fip/v1/videos/{videoid}/{ts}.ts
            - Method=GET
          filters:
            # 视频片段
            - SetPath=/api/v1/video/{ts}.ts

        - id: vpp_put_video
          uri: ${VPP_DATA_SERVICE:http://vpp:8082}
          predicates:
            - Path=/fip/v1/videos/{videoid}/data
            - Method=PUT
          filters:
            - name: RequestSize
              args:
                maxSize: 10000000
            # 上传视频数据
            - SetPath=/api/v1/upload/{videoid}

        - id: fip
          uri: ${FIP_MAIN_SERVICE:http://fip-main:8090}
          predicates:
            - Path=/fip/v1/**
          filters:
            - RewritePath= /fip/v1/(?<segment>.*),/$\{segment}
            - CheckAuth=false

        - id: auth
          uri: ${PILOT_SERVICE:http://pilot:8080}
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /oauth/$\{segment}

        - id: web
          uri: ${FRONTEND_WEB_SERVICE:http://frontend-web:80}
          predicates:
            - Path=/api/web/**
          filters:
            - RewritePath=/api/web/(?<segment>.*),/$\{segment}

        - id: media
          uri: ${FRONTEND_NODE_SERVICE:http://frontend-node:8000}
          predicates:
            - Path=/identification/api/v1/medias/**
          filters:
            - RewritePath=/identification/api/v1/medias/(?<segment>.*),/media/$\{segment}
            - CheckAuth=false

        - id: node
          uri: ${FRONTEND_NODE_SERVICE:http://frontend-node:8000}
          predicates:
            - Path=/identification/**
          filters:
            - CheckAuth=false

        - id: root
          uri: ${FRONTEND_WEB_SERVICE:http://frontend-web:80}
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<segment>.*), /#/login

auth-config:
  oauthServer: ${PILOT_SERVICE:http://pilot:8080}

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL:info}
    root: ${LOGGING_LEVEL:info}

