version: "2"

services:
  mysql:
    image: mysql:5.7.14
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: can123mima
      MYSQL_DATABASE: kg_graph
      MYSQL_USER: kg_graph
      MYSQL_PASSWORD: kg_graph
    volumes:
      - ./data/mysql:/var/lib/mysql

  kggraph:
    image: it-artifactory.yitu-inc.com/docker-local/big-data/kg-graph:v0.2.10
    ports:
      - 8080:8080
    volumes:
        # 数据存储的目录
      - ./data/hugegraph-0.10.4/:/app/hugegraph-0.10.4/rocksdb-data/
        # 执行日志目录
      - ./logs/hugegraph-0.10.4/:/app/hugegraph-0.10.4/logs/
      - ./conf/hugegraph-0.10.4/gremlin-server.yaml:/app/hugegraph-0.10.4/conf/gremlin-server.yaml
      - ./conf/hugegraph-0.10.4/rest-server.properties:/app/hugegraph-0.10.4/conf/rest-server.properties
      - ./conf/hugegraph-0.10.4/yituKg.properties:/app/hugegraph-0.10.4/conf/yituKg.properties

    environment:
      - TZ=Asia/Shanghai
      - SW_AGENT_NAME=kggraph
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=oap:11800

  kggraph-studio:
    image: it-artifactory.yitu-inc.com/docker-local/big-data/kg-graph-studio:v0.2.10
    ports:
      - 8088:8088
    volumes:
      - ./conf/hugegraph-studio-0.10.0/:/app/hugegraph-studio-0.10.0/conf/
  
  kg-meta:
    image: it-artifactory.yitu-inc.com/docker-local/big-data/kg-meta:v0.2.10
    ports:
      -  10843:10843
    links:
      - mysql
    volumes: 
      - ./conf/bdp-kg-meta/application-dev.yml:/app/config/application-dev.yml
      - ./sql/init.sql:/app/sql/metadata_schema.sql
