#PILOT_SERVICE: http://10.10.25.87:8080
OAUTH_CLIENT_ID: fipLinkClient
OAUTH_CLIENT_SECRET: 1Tu_Fip_Link_User
FIP_MAIN_SERVICE: http://fip-main:8090
PUSHGATEWAY_SERVICE: http://pushgateway:9091

server:
  port: ${APP_PORT:9080}


spring:
  cloud:
    gateway:
      routes:

        - id: login
          uri: ${PILOT_SERVICE:http://pilot:8080}
          predicates:
            - Path=/fip/v1/auth/login
          filters:
            - MutateContentType=JSON_TO_FORM_URLENCODED
            - AddOAuthClient=fipClient, 1Tu_Fip_User
            - SetPath=/oauth/token


        - id: fip1
          uri: ${FIP_MAIN_SERVICE:http://fip-main:8090}
          predicates:
            - Path=/fip/v1/clusters/**
          filters:
            - RewritePath= /fip/v1/(?<segment>.*),/$\{segment}
            - CheckAuth=false

        - id: fip2
          uri: ${FIP_MAIN_SERVICE:http://fip-main:8090}
          predicates:
            - Path=/fip/v1/repositories/tasks/face-retrievals
          filters:
            - RewritePath= /fip/v1/(?<segment>.*),/$\{segment}
            - CheckAuth=false


        - id: fip3
          uri: ${FIP_MAIN_SERVICE:http://fip-main:8090}
          predicates:
            - Path=/fip/v1/images/contents/*
          filters:
            - RewritePath= /fip/v1/(?<segment>.*),/$\{segment}
            - CheckAuth=false

        - id: fip4
          uri: ${FIP_MAIN_SERVICE:http://fip-main:8090}
          predicates:
            - Path=/fip/v1/repositories
          filters:
            - RewritePath= /fip/v1/(?<segment>.*),/$\{segment}
#            - CheckAuth=false

        - id: fip5
          uri: ${FIP_MAIN_SERVICE:http://fip-main:8090}
          predicates:
            - Path=/fip/v1/repositories/*
          filters:
            - RewritePath= /fip/v1/(?<segment>.*),/$\{segment}
            - CheckAuth=false

        - id: auth
          uri: ${PILOT_SERVICE:http://pilot:8080}
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /oauth/$\{segment}

        - id: pushgateway
          uri: ${PUSHGATEWAY_SERVICE:http://pushgateway:9091}
          predicates:
            - Path=/prometheus/pushgateway/**
          filters:
            - RewritePath=/prometheus/pushgateway/(?<segment>.*),/$\{segment}

auth-config:
  oauthServer: ${PILOT_SERVICE:http://pilot:8080}

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL:info}
    root: ${LOGGING_LEVEL:info}
