version: "2"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: on-failure
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: on-failure
