version: '2'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: star
      MYSQL_USER: star
      MYSQL_PASSWORD: star

