version: "3"
services:
  redis:
    image: redis:5.0.4
    ports:
      - 6379:6379

  mysql:
    image: mysql:5.7.14
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: Rootfip123
      MYSQL_DATABASE: pilot
      MYSQL_USER: pilot
      MYSQL_PASSWORD: Pilot123

  fip-mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  vpp:
    image: it-artifactory.yitu-inc.com/docker-local/big-data/fip/vpp:20190805
    ports:
      - 8082:8082
    links:
      - fip-mongo
    volumes:
      - ./vpp/config/application.properties:/app/config/application.properties

  pilot:
    image: it-artifactory.yitu-inc.com/zagu-docker/pilot:fip_1.3.0
    ports:
      - 8080:8080
    links:
      - redis
      - mysql
    environment:
      MYSQL_DB_NAME: pilot
      MYSQL_DB_USERNAME: pilot
      MYSQL_DB_PASSWORD: Pilot123

  fip-main:
#    image: it-artifactory.yitu-inc.com/docker-local/big-data/fip/fip-main:98149654
    image: fip-main:f00a86a2
    links:
      - fip-mongo
      - vpp
      - repo-manager
    ports:
      - 8090:8090
      - 3456:3456
    volumes:
      - ./fip-main/config/application.yaml:/app/config/application.yaml
      - ./fip-main/config/application-flash3_clusters.yaml:/app/config/application-flash3_clusters.yaml
      - ./fip-main/config/application-fp_clusters.yaml:/app/config/application-fp_clusters.yaml
    environment:
      LICENSE_HOST: 10.40.80.18
      LICENSE_PORT: 7411
      LICENSE_ENABLED: 'false'
      #如果大螺丝在外部, 那这两个IP要配成自己机器的IP, 视频分析才能work
      LUCIFRON_HOST: 10.40.80.43
      DEBUG_OUTSIDE_RAGNAROS: "true"
      DEBUG_EXTERNAL_IP: 10.10.25.87
      LOCAL_HOST: 10.10.25.87
      #根据联动需求配置
      CLUSTER_ID: SH_SH_01
      CLUSTER_NAME: 上海市局一号
      CLUSTER_PROVINCE: 上海市
      CLUSTER_CITY: 上海市
      CLUSTER_COUNTY: 
      JOB_CLUSTER_MONITOR_COLLECT: '0 */1 * * * ?'
      JOB_CLUSTER_MONITOR_FETCH: '10 */1 * * * ?'
      JOB_CLUSTER_MONITOR_REPORT: '20 */1 * * * ?'
      EXCLUDE_REPORT_CLUSTERS:
      INCLUDE_REPORT_CLUSTERS:


  frontend-web:
    image: it-artifactory.yitu-inc.com/docker-local/gitlab-ci-artifacts/portrait-identification/website:release-hulk.1-ed214045
    ports:
      - 4000:80
    volumes:
      - ./website/config.template.js:/usr/share/nginx/html/config.js

  frontend-node:
    image: it-artifactory.yitu-inc.com/ipiw-docker/ipiw-node:release-hulk.1-01ee858f
    ports:
      - 4100:8000
    environment:
      PILOT_URL: http://pilot:8080
      MONGO_URL: mongodb://fip-mongo:27017/identification_platform
    links:
      - fip-mongo
      - pilot

  api-gateway:
    image: it-artifactory.yitu-inc.com/zagu-docker/api-gateway:release_1.4.0
    links:
      - pilot
      - fip-main
    ports:
      - 8060:8080
    volumes:
      - ./gateway/config/application.yml:/app/config/application.yml
      - ./gateway/config/rsaserver.keystore:/app/config/rsaserver.keystore

  p2p-api-gateway:
    image: it-artifactory.yitu-inc.com/zagu-docker/api-gateway:release_1.4.0
    links:
      - pilot
      - fip-main
    ports:
      - 9080:9080
    volumes:
      - ./p2p-gateway/config/application.yml:/app/config/application.yml

  p2p-component:
    image: it-artifactory.yitu-inc.com/docker-local/p2p:release_2-0-1-50f90995
    ports:
      - 7093:7093
      - 8443:8443
      - 7600:7600
    environment:
      SPRING_APPLICATION_JSON: '
                               {
                                 "PROXY_PORT": 7093,
                                 "HTTPS_PORT": 8443,
                                 "HTTP_PORT": 7600,
                                 "current_cluster_id": "SH_SH_01",
                                 "GATEWAY_HOST": "p2p-api-gateway",
                                 "GATEWAY_PORT": 9080,
                                 "p2p": {
                                   "routes": {
                                     "static": {
                                       "directRoute": {
                                         "SH_SH_01": "10.10.25.87:8443:7600",
                                         "SH_SH_02": "10.10.25.87:18443:17600",
                                         "SH_SH_CN_01": "10.10.25.87:28443:27600",
                                         "SC_01": "10.10.25.162:8443:7600",
                                         "SC_CD_WH_01": "10.10.25.162:18443:17600",
                                         "JX_JJ_01": "10.10.25.162:28443:27600"
                                       },
                                       "indirectRoute": {}
                                     }
                                   }
                                 }
                               }
                               '
                               
  fp-proxy:
    image: it-artifactory.yitu-inc.com/docker-local/gitlab-ci-artifacts/fip/fp-proxy:dev-8ec77215
    links:
      - api-gateway
    ports:
      - 7500:7500
      - 7530:7530
      - 9900:9900
      - 9200:9200
      - 7300:7300

  image-server:
    image: it-artifactory.yitu-inc.com/docker-local/gitlab-ci-artifacts/cvpf/image-server:release-0.1.0-ab1f7a9b
    environment:
      MONGO_URI: mongodb://fip-mongo:27017/cvpf_image_server
    ports:
      - 8382:8382
    links:
      - fip-mongo

  repo-manager:
    image: it-artifactory.yitu-inc.com/docker-local/repository-manager:feature_hcwang_indexforsubject-d064090a
    environment:
      MONGO_URI: mongodb://fip-mongo:27017/cvpf_repository_manager
      FaceImageFeatureExtractOperator_Group: sample-feature-extract
      FaceAnnoImageFeatureExtractOperator_Group: sample-feature-extract
      FaceRetrievalOperator_Group: sample-retrieval
      RAGNAROS_HOST: 10.40.80.43
      RAGNAROS_PORT: 9980
      REPO_DEFAULT_MODEL: 3060
      SIS_HOST: image-server
      SIS_PORT: 8382
      SERVER_PORT: 8585
      ENABLE_ROTATION: 'True'
    entrypoint: ["java", "-jar", "-Xmx8192M", "-Dlogging.level.root=INFO", "/app/app.jar"]
    ports:
      - 8585:8585
    links:
      - fip-mongo
      - image-server


  prometheus:
    image: prom/prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/node_down.yml:/etc/prometheus/node_down.yml
    ports:
      - 9090:9090
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
