version: "3"

services:
  redis:
    image: redis:5.0.4
    ports:
      - 6379:6379

  mysql:
    image: mysql:5.7.14
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: Rootfip123
      MYSQL_DATABASE: pilot
      MYSQL_USER: pilot
      MYSQL_PASSWORD: Pilot123

  fip-mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  vpp:
    image: 10.40.80.18:5001/vpp:20190805
    ports:
      - 8082:8082
    links:
      - fip-mongo
    volumes:
      - /mnt/WXEG0048_ssd/fip_compose/dev/vpp/config/application.properties:/app/config/application.properties

  pilot:
    image: it-artifactory.yitu-inc.com/zagu-docker/pilot:fip_1.3.0
    ports:
      - 8080:8080
    links:
      - redis
      - mysql
    environment:
      MYSQL_DB_NAME: pilot
      MYSQL_DB_USERNAME: pilot
      MYSQL_DB_PASSWORD: Pilot123

  fip-main:
    image: fip-main:c2579d08
    links:
      - fip-mongo
      - vpp
      - repo-manager
    ports:
      - 8382:8090
      - 3456:3456
    environment:
      LUCIFRON_HOST: 10.40.80.43

      DEBUG_OUTSIDE_RAGNAROS: "true"
      #如果大螺丝在外部, 那这两个IP要配成自己机器的IP, 视频分析才能work
      DEBUG_EXTERNAL_IP: 10.10.25.87
      LOCAL_HOST: 10.10.25.87

      LICENSE_HOST: 10.40.50.172
      LICENSE_PORT: 7411
      LICENSE_ENABLED: "false"

      CLUSTER_ID: yitu001_id
      CLUSTER_NAME: yitu001_name
      CLUSTER_PROVINCE: shandong
      CLUSTER_CITY: jinan
      CLUSTER_COUNTY: somewhere

      P2P_PROXY_URL: 127.0.0.1
      P2P_PROXY_PORT: 7092
      P2P_SERVICE_PORT: 6600

  frontend-web:
    image: it-artifactory.yitu-inc.com/docker-local/gitlab-ci-artifacts/portrait-identification/website:master-dd553c1b
    ports:
      - 4000:80
    volumes:
      - /mnt/WXEG0048_ssd/fip_compose/dev/node/config.template.js:/usr/share/nginx/html/config.js

      # - /mnt/WXEG0048_ssd/fip_compose/dev/node/nginx.conf:/etc/nginx/nginx.conf
      # - /mnt/WXEG0048_ssd/fip_compose/dev/node/default.conf:/etc/nginx/conf.d/default.conf

  frontend-node:
    image: it-artifactory.yitu-inc.com/ipiw-docker/ipiw-node:master-1eb31d9a
    ports:
      - 4100:8000
    environment:
      PILOT_URL: http://pilot:8080
      MONGO_URL: mongodb://fip-mongo:27017/identification_platform
    links:
      - fip-mongo
      - pilot

  api-gateway:
    image: it-artifactory.yitu-inc.com/zagu-docker/api-gateway:release_1.4.0
    links:
      - pilot
      - fip-main
    ports:
      - 8060:8080
    volumes:
      - /mnt/WXEG0048_ssd/fip_compose/dev/gateway/config/application.yml:/app/config/application.yml
      - /mnt/WXEG0048_ssd/fip_compose/dev/gateway/config/rsaserver.keystore:/app/config/rsaserver.keystore

  p2p-api-gateway:
    image: it-artifactory.yitu-inc.com/docker-local/p2p:feature_log_trace-287e50fb
    links:
      - pilot
      - fip-main
    ports:
      - 9080:9080
    volumes:
      - /mnt/WXEG0048_ssd/fip_compose/dev/gateway/config/application-p2p.yml:/app/config/application.yml

  fp-proxy:
    image: it-artifactory.yitu-inc.com/docker-local/gitlab-ci-artifacts/fip/fp-proxy:dev-8ec77215
    links:
      - api-gateway
    ports:
      - 7500:7500
      - 7530:7530
      - 9900:9900
      - 9200:9200
      - 7300:7300

  image-server:
    image: it-artifactory.yitu-inc.com/docker-local/gitlab-ci-artifacts/cvpf/image-server:release-0.1.0-ab1f7a9b
    environment:
      MONGO_URI: mongodb://fip-mongo:27017/cvpf_image_server
    ports:
      - 8383:8382
    links:
      - fip-mongo

  repo-manager:
    image: it-artifactory.yitu-inc.com/docker-local/repository-manager:feature_hcwang_indexforsubject-d064090a
    environment:
      MONGO_URI: mongodb://fip-mongo:27017/cvpf_repository_manager
      FaceImageFeatureExtractOperator_Group: sample-feature-extract
      FaceAnnoImageFeatureExtractOperator_Group: sample-feature-extract
      FaceRetrievalOperator_Group: sample-retrieval
      RAGNAROS_HOST: 10.40.80.43
      RAGNAROS_PORT: 9980
      REPO_DEFAULT_MODEL: 3060
      SIS_HOST: image-server
      SIS_PORT: 8382
      SERVER_PORT: 8585
      ENABLE_ROTATION: 'True'
    entrypoint: ["java", "-jar", "-Dlogging.level.root=INFO", "/app/app.jar"]
    ports:
      - 8585:8585
    links:
      - fip-mongo
      - image-server
