version: '2.1'
services:
  zookeeper:
    image: 'it-artifactory.yitu-inc.com/docker-local/big-data/zookeeper:3.4.14'
    ports:
      - '2181:2181'
    volumes:
      - ./config/zoo.cfg:/opt/zookeeper-3.4.14/conf/zoo.cfg
      - ./data/zookeeper:/data/zookeeper

  kafka:
    image: 'it-artifactory.yitu-inc.com/docker-local/big-data/kafka:2.2.0'
    ports:
      - '9092:9092'
    volumes:
      - ./config/kafka-server.properties:/opt/kafka_2.12-2.2.0/config/server.properties
      - ./data/kafka:/data/kafka-logs
