version: "3"
services:

  fip-main:
#    image: it-artifactory.yitu-inc.com/docker-local/big-data/fip/fip-main:98149654
    image: fip-main:5c9898b9
    ports:
      - 28090:8090
      - 23456:3456
    volumes:
      - ./fip-main/config/application.yaml:/app/config/application.yaml
      - ./fip-main/config/application-flash3_clusters.yaml:/app/config/application-flash3_clusters.yaml
      - ./fip-main/config/application-fp_clusters.yaml:/app/config/application-fp_clusters.yaml
    environment:
      LICENSE_HOST: 10.40.80.18
      LICENSE_PORT: 7411
      LICENSE_ENABLED: 'false'
      VIDEO_CALLBACK_PORT: 3467
      LUCIFRON_HOST: 10.40.80.43
      #根据需求填写
      CLUSTER_ID: SH_SH_CN_01
      CLUSTER_NAME: 上海市长宁分局
      CLUSTER_PROVINCE: 上海市
      CLUSTER_CITY: 上海市
      CLUSTER_COUNTY: 长宁区
      JOB_CLUSTER_MONITOR_COLLECT: '0/30 * * * * ?'
      JOB_CLUSTER_MONITOR_FETCH: '10/30 * * * * ?'
      JOB_CLUSTER_MONITOR_REPORT: '20/30 * * * * ?'
      EXCLUDE_REPORT_CLUSTERS:
      INCLUDE_REPORT_CLUSTERS:
      #引用外部的基础设施,ip改成自己机器ip
      REDIS_HOST: 10.10.25.87
      MONGODB_HOST: 10.10.25.87
      VPP_HOST: 10.10.25.87
      CVPF_REPO_HOST: 10.10.25.87
      PILOT_URL: http://10.10.25.87:8080
      #如果大螺丝在外部, 那这两个IP要配成自己机器的IP, 视频分析才能work
      DEBUG_OUTSIDE_RAGNAROS: "true"
      DEBUG_EXTERNAL_IP: 10.10.25.87
      LOCAL_HOST: 10.10.25.87
      

  p2p-api-gateway:
    image: it-artifactory.yitu-inc.com/zagu-docker/api-gateway:release_1.4.0
    links:
      - fip-main
    ports:
      - 29080:9080
    volumes:
      - ./p2p-gateway/config/application.yml:/app/config/application.yml
    environment:
      PILOT_SERVICE: 'http://10.10.25.87:8080'

  p2p-component:
    image: it-artifactory.yitu-inc.com/docker-local/p2p:release_2-0-1-50f90995
    ports:
      - 27093:7093
      - 28443:8443
      - 27600:7600
    #修改此处的配置文件，根据联动需求填写
    environment:
      SPRING_APPLICATION_JSON: '
                               {
                                 "PROXY_PORT": 7093,
                                 "HTTPS_PORT": 8443,
                                 "HTTP_PORT": 7600,
                                 "current_cluster_id": "SH_SH_CN_01",
                                 "GATEWAY_HOST": "p2p-api-gateway",
                                 "GATEWAY_PORT": 9080,
                                 "p2p": {
                                   "routes": {
                                     "static": {
                                       "directRoute": {
                                         "SH_SH_01": "10.10.25.87:8443:7600",
                                         "SH_SH_02": "10.10.25.87:18443:17600",
                                         "SH_SH_CN_01": "10.10.25.87:28443:27600",
                                         "SC_01": "10.10.25.162:8443:7600",
                                         "SC_CD_WH_01": "10.10.25.162:18443:17600",
                                         "JX_JJ_01": "10.10.25.162:28443:27600"
                                       },
                                       "indirectRoute": {}
                                     }
                                   }
                                 }
                               }
                               '


  prometheus:
    image: prom/prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/node_down.yml:/etc/prometheus/node_down.yml
    ports:
      - 29090:9090
  pushgateway:
    image: prom/pushgateway
    ports:
      - 29091:9091



