version: "3"

services:
  mongo:
#    image: mongo:4.0.6
    image: it-artifactory.yitu-inc.com/docker-pro/opod/mongo:3.4-xenial
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./mongo:/data/db
